version: '2'

services:
  server:
    image: visualjeff/simple-http-server:0.0.1
    volumes:
      - "/home/deploy/projects/${PROJECT_NAME}/dist:/data"
    ports:
      - "${NEXT_PORT}:8080"
    expose:
      - 8080
    restart: always
    external_links:
      - mysql:db
    environment:
      DB_HOST: db:3306
      DB_USER: spaces
      DB_PASSWORD: zah0Eegh
      DB_NAME: "${PROJECT_NAME}"
      VIRTUAL_HOST: "${PROJECT_NAME}.lab.spaceshiplabs.com,salama.io,www.salama.io"
      LETSENCRYPT_HOST: "${PROJECT_NAME}.lab.spaceshiplabs.com,salama.io,www.salama.io"
      LETSENCRYPT_EMAIL: "aero.uriel@gmail.com"
      ALLOW_OVERRIDE: "true"
    network_mode: bridge
